[2024-12-08T02:36:15.966+0000] {processor.py:186} INFO - Started process (PID=602) to work on /opt/airflow/dags/weather.py
[2024-12-08T02:36:15.968+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T02:36:16.004+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:36:16.004+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T02:36:16.073+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:36:16.067+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 64
    
    ^
IndentationError: expected an indented block
[2024-12-08T02:36:16.074+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-08T02:36:16.248+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.398 seconds
[2024-12-08T02:36:24.204+0000] {processor.py:186} INFO - Started process (PID=603) to work on /opt/airflow/dags/weather.py
[2024-12-08T02:36:24.217+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T02:36:24.238+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:36:24.219+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T02:36:24.249+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:36:24.247+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 1
    from airflow import DAGfrom airflow.providers.standard.operators.python import (
                                ^
SyntaxError: invalid syntax
[2024-12-08T02:36:24.263+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-08T02:36:24.443+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.256 seconds
[2024-12-08T02:36:26.477+0000] {processor.py:186} INFO - Started process (PID=604) to work on /opt/airflow/dags/weather.py
[2024-12-08T02:36:26.479+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T02:36:26.491+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:36:26.490+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T02:36:26.516+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:36:26.514+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 69
    
    ^
IndentationError: expected an indented block
[2024-12-08T02:36:26.522+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-08T02:36:26.705+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.355 seconds
[2024-12-08T02:36:57.681+0000] {processor.py:186} INFO - Started process (PID=611) to work on /opt/airflow/dags/weather.py
[2024-12-08T02:36:57.692+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T02:36:57.713+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:36:57.710+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T02:36:57.752+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:36:57.750+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 69
    
    ^
IndentationError: expected an indented block
[2024-12-08T02:36:57.752+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-08T02:36:57.959+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.331 seconds
[2024-12-08T02:37:28.558+0000] {processor.py:186} INFO - Started process (PID=618) to work on /opt/airflow/dags/weather.py
[2024-12-08T02:37:28.573+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T02:37:28.588+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:37:28.576+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T02:37:28.614+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:37:28.603+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 69
    
    ^
IndentationError: expected an indented block
[2024-12-08T02:37:28.615+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-08T02:37:28.716+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.219 seconds
[2024-12-08T02:37:59.619+0000] {processor.py:186} INFO - Started process (PID=625) to work on /opt/airflow/dags/weather.py
[2024-12-08T02:37:59.659+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T02:37:59.730+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:37:59.711+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T02:37:59.778+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:37:59.777+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 69
    
    ^
IndentationError: expected an indented block
[2024-12-08T02:37:59.779+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-08T02:38:00.001+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.449 seconds
[2024-12-08T02:38:06.265+0000] {processor.py:186} INFO - Started process (PID=626) to work on /opt/airflow/dags/weather.py
[2024-12-08T02:38:06.276+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T02:38:06.289+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:38:06.279+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T02:38:06.323+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:38:06.310+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 70
    
    ^
IndentationError: expected an indented block
[2024-12-08T02:38:06.323+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-08T02:38:06.492+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.256 seconds
[2024-12-08T02:38:07.770+0000] {processor.py:186} INFO - Started process (PID=627) to work on /opt/airflow/dags/weather.py
[2024-12-08T02:38:07.771+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T02:38:07.777+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:38:07.776+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T02:38:07.813+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:38:07.801+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 2, in <module>
    from airflow.providers.standard.operators.python import (
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2024-12-08T02:38:07.814+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-08T02:38:07.892+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.181 seconds
[2024-12-08T02:38:09.784+0000] {processor.py:186} INFO - Started process (PID=628) to work on /opt/airflow/dags/weather.py
[2024-12-08T02:38:09.785+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T02:38:09.803+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:38:09.803+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T02:38:09.834+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:38:09.828+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 2, in <module>
    from airflow.providers.standard.operators.python import (
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2024-12-08T02:38:09.835+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-08T02:38:10.067+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.316 seconds
[2024-12-08T02:38:11.511+0000] {processor.py:186} INFO - Started process (PID=629) to work on /opt/airflow/dags/weather.py
[2024-12-08T02:38:11.512+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T02:38:11.536+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:38:11.535+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T02:38:11.622+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:38:11.601+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 2, in <module>
    from airflow.providers.standard.operators.python import (
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2024-12-08T02:38:11.640+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-08T02:38:11.896+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.495 seconds
[2024-12-08T02:38:13.290+0000] {processor.py:186} INFO - Started process (PID=636) to work on /opt/airflow/dags/weather.py
[2024-12-08T02:38:13.291+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T02:38:13.322+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:38:13.318+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T02:38:13.365+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:38:13.364+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 2, in <module>
    from airflow.providers.standard.operators.python import (
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2024-12-08T02:38:13.370+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-08T02:38:13.479+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.256 seconds
[2024-12-08T02:38:14.762+0000] {processor.py:186} INFO - Started process (PID=637) to work on /opt/airflow/dags/weather.py
[2024-12-08T02:38:14.763+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T02:38:14.784+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:38:14.783+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T02:38:14.819+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:38:14.818+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 2, in <module>
    from airflow.providers.standard.operators.python import (
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2024-12-08T02:38:14.855+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-08T02:38:14.979+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.350 seconds
[2024-12-08T02:38:16.852+0000] {processor.py:186} INFO - Started process (PID=638) to work on /opt/airflow/dags/weather.py
[2024-12-08T02:38:16.854+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T02:38:16.865+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:38:16.864+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T02:38:16.894+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:38:16.891+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 2, in <module>
    from airflow.providers.standard.operators.python import (
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2024-12-08T02:38:16.897+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-08T02:38:17.020+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.201 seconds
[2024-12-08T02:38:24.109+0000] {processor.py:186} INFO - Started process (PID=639) to work on /opt/airflow/dags/weather.py
[2024-12-08T02:38:24.123+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T02:38:24.140+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:38:24.139+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T02:38:24.216+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:38:24.209+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 2, in <module>
    from airflow.providers.standard.operators.python import (
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2024-12-08T02:38:24.217+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-08T02:38:24.326+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.261 seconds
[2024-12-08T02:38:26.476+0000] {processor.py:186} INFO - Started process (PID=640) to work on /opt/airflow/dags/weather.py
[2024-12-08T02:38:26.493+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T02:38:26.542+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:38:26.525+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T02:38:26.595+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:38:26.585+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 2, in <module>
    from airflow.providers.standard.operators.python import (
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2024-12-08T02:38:26.596+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-08T02:38:26.863+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.441 seconds
[2024-12-08T02:38:29.168+0000] {processor.py:186} INFO - Started process (PID=641) to work on /opt/airflow/dags/weather.py
[2024-12-08T02:38:29.170+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T02:38:29.183+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:38:29.183+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T02:38:29.224+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:38:29.213+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 2, in <module>
    from airflow.providers.standard.operators.python import (
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2024-12-08T02:38:29.225+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-08T02:38:29.377+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.257 seconds
[2024-12-08T02:38:30.238+0000] {processor.py:186} INFO - Started process (PID=642) to work on /opt/airflow/dags/weather.py
[2024-12-08T02:38:30.255+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T02:38:30.274+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:38:30.274+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T02:38:30.346+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:38:30.340+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 2, in <module>
    from airflow.providers.standard.operators.python import (
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2024-12-08T02:38:30.353+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-08T02:38:30.486+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.286 seconds
[2024-12-08T02:38:32.777+0000] {processor.py:186} INFO - Started process (PID=643) to work on /opt/airflow/dags/weather.py
[2024-12-08T02:38:32.778+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T02:38:32.794+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:38:32.793+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T02:38:32.831+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:38:32.830+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 2, in <module>
    from airflow.providers.standard.operators.python import (
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2024-12-08T02:38:32.832+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-08T02:38:32.941+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.208 seconds
[2024-12-08T02:38:54.539+0000] {processor.py:186} INFO - Started process (PID=649) to work on /opt/airflow/dags/weather.py
[2024-12-08T02:38:54.544+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T02:38:54.551+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:38:54.547+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T02:38:54.574+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:38:54.572+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 14
    def 
        ^
SyntaxError: invalid syntax
[2024-12-08T02:38:54.580+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-08T02:38:54.738+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.222 seconds
[2024-12-08T02:38:57.770+0000] {processor.py:186} INFO - Started process (PID=650) to work on /opt/airflow/dags/weather.py
[2024-12-08T02:38:57.800+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T02:38:57.815+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:38:57.815+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T02:38:57.845+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:38:57.838+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 14
    def ingestion
                 ^
SyntaxError: invalid syntax
[2024-12-08T02:38:57.845+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-08T02:38:58.107+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.421 seconds
[2024-12-08T02:39:01.100+0000] {processor.py:186} INFO - Started process (PID=651) to work on /opt/airflow/dags/weather.py
[2024-12-08T02:39:01.105+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T02:39:01.126+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:39:01.125+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T02:39:01.161+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:39:01.150+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 14
    def ingestion_weather
                         ^
SyntaxError: invalid syntax
[2024-12-08T02:39:01.162+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-08T02:39:01.276+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.228 seconds
[2024-12-08T02:39:03.651+0000] {processor.py:186} INFO - Started process (PID=652) to work on /opt/airflow/dags/weather.py
[2024-12-08T02:39:03.652+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T02:39:03.673+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:39:03.673+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T02:39:03.734+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:39:03.712+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 14
    def ingestion_weather:
                         ^
SyntaxError: invalid syntax
[2024-12-08T02:39:03.735+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-08T02:39:04.022+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.495 seconds
[2024-12-08T02:39:05.238+0000] {processor.py:186} INFO - Started process (PID=653) to work on /opt/airflow/dags/weather.py
[2024-12-08T02:39:05.252+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T02:39:05.276+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:39:05.275+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T02:39:05.312+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:39:05.301+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 16
    cache_session = requests_cache.CachedSession('.cache', expire_after = 3600)
    ^
IndentationError: expected an indented block
[2024-12-08T02:39:05.313+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-08T02:39:05.477+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.322 seconds
[2024-12-08T02:39:11.479+0000] {processor.py:186} INFO - Started process (PID=654) to work on /opt/airflow/dags/weather.py
[2024-12-08T02:39:11.488+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T02:39:11.512+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:39:11.511+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T02:39:11.553+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:39:11.552+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 2, in <module>
    from airflow.providers.standard.operators.python import (
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2024-12-08T02:39:11.554+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-08T02:39:11.659+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.305 seconds
[2024-12-08T02:39:14.605+0000] {processor.py:186} INFO - Started process (PID=661) to work on /opt/airflow/dags/weather.py
[2024-12-08T02:39:14.606+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T02:39:14.655+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:39:14.655+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T02:39:14.799+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:39:14.758+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 2, in <module>
    from airflow.providers.standard.operators.python import (
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2024-12-08T02:39:14.802+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-08T02:39:15.081+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.613 seconds
[2024-12-08T02:39:33.676+0000] {processor.py:186} INFO - Started process (PID=662) to work on /opt/airflow/dags/weather.py
[2024-12-08T02:39:33.679+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T02:39:33.688+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:39:33.687+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T02:39:33.706+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:39:33.704+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 2, in <module>
    from airflow.providers.standard.operators.python import (
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2024-12-08T02:39:33.708+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-08T02:39:33.759+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.105 seconds
[2024-12-08T02:39:42.246+0000] {processor.py:186} INFO - Started process (PID=663) to work on /opt/airflow/dags/weather.py
[2024-12-08T02:39:42.258+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T02:39:42.270+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:39:42.261+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T02:39:42.299+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:39:42.297+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 2, in <module>
    from airflow.providers.standard.operators.python import (
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2024-12-08T02:39:42.300+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-08T02:39:42.440+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.234 seconds
[2024-12-08T02:39:44.847+0000] {processor.py:186} INFO - Started process (PID=670) to work on /opt/airflow/dags/weather.py
[2024-12-08T02:39:44.852+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T02:39:44.875+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:39:44.875+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T02:39:44.913+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:39:44.903+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 2, in <module>
    from airflow.providers.standard.operators.python import (
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2024-12-08T02:39:44.914+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-08T02:39:45.075+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.315 seconds
[2024-12-08T02:39:51.468+0000] {processor.py:186} INFO - Started process (PID=671) to work on /opt/airflow/dags/weather.py
[2024-12-08T02:39:51.478+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T02:39:51.490+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:39:51.481+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T02:39:51.511+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:39:51.507+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 2, in <module>
    from airflow.providers.standard.operators.python import (
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2024-12-08T02:39:51.512+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-08T02:39:51.650+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.224 seconds
[2024-12-08T02:39:58.899+0000] {processor.py:186} INFO - Started process (PID=672) to work on /opt/airflow/dags/weather.py
[2024-12-08T02:39:58.915+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T02:39:58.935+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:39:58.918+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T02:39:58.998+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:39:58.977+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 2, in <module>
    from airflow.providers.standard.operators.python import (
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2024-12-08T02:39:58.999+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-08T02:39:59.299+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.480 seconds
[2024-12-08T02:40:09.723+0000] {processor.py:186} INFO - Started process (PID=673) to work on /opt/airflow/dags/weather.py
[2024-12-08T02:40:09.729+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T02:40:09.753+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:40:09.731+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T02:40:09.789+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:40:09.782+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 2, in <module>
    from airflow.providers.standard.operators.python import (
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2024-12-08T02:40:09.790+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-08T02:40:09.913+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.251 seconds
[2024-12-08T02:40:10.856+0000] {processor.py:186} INFO - Started process (PID=674) to work on /opt/airflow/dags/weather.py
[2024-12-08T02:40:10.857+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T02:40:10.880+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:40:10.879+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T02:40:10.917+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:40:10.906+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 2, in <module>
    from airflow.providers.standard.operators.python import (
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2024-12-08T02:40:10.918+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-08T02:40:11.170+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.392 seconds
[2024-12-08T02:40:42.091+0000] {processor.py:186} INFO - Started process (PID=681) to work on /opt/airflow/dags/weather.py
[2024-12-08T02:40:42.095+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T02:40:42.103+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:40:42.098+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T02:40:42.116+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:40:42.111+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 2, in <module>
    from airflow.providers.standard.operators.python import (
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2024-12-08T02:40:42.119+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-08T02:40:42.186+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.188 seconds
[2024-12-08T02:41:12.739+0000] {processor.py:186} INFO - Started process (PID=688) to work on /opt/airflow/dags/weather.py
[2024-12-08T02:41:12.749+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T02:41:12.762+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:41:12.752+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T02:41:12.791+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:41:12.774+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 2, in <module>
    from airflow.providers.standard.operators.python import (
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2024-12-08T02:41:12.792+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-08T02:41:12.879+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.196 seconds
[2024-12-08T02:41:26.109+0000] {processor.py:186} INFO - Started process (PID=695) to work on /opt/airflow/dags/weather.py
[2024-12-08T02:41:26.113+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T02:41:26.120+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:41:26.119+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T02:41:26.132+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:41:26.131+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 2, in <module>
    from airflow.providers.standard.operators.python import (
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2024-12-08T02:41:26.133+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-08T02:41:26.282+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.186 seconds
[2024-12-08T02:41:57.163+0000] {processor.py:186} INFO - Started process (PID=702) to work on /opt/airflow/dags/weather.py
[2024-12-08T02:41:57.173+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T02:41:57.187+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:41:57.186+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T02:41:57.219+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:41:57.201+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 2, in <module>
    from airflow.providers.standard.operators.python import (
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2024-12-08T02:41:57.220+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-08T02:41:57.316+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.199 seconds
[2024-12-08T02:42:27.906+0000] {processor.py:186} INFO - Started process (PID=709) to work on /opt/airflow/dags/weather.py
[2024-12-08T02:42:27.909+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T02:42:27.913+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:42:27.911+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T02:42:27.919+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:42:27.918+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 2, in <module>
    from airflow.providers.standard.operators.python import (
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2024-12-08T02:42:27.921+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-08T02:42:27.988+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.098 seconds
[2024-12-08T02:42:58.519+0000] {processor.py:186} INFO - Started process (PID=715) to work on /opt/airflow/dags/weather.py
[2024-12-08T02:42:58.558+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T02:42:58.588+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:42:58.587+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T02:42:58.641+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:42:58.620+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 2, in <module>
    from airflow.providers.standard.operators.python import (
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2024-12-08T02:42:58.642+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-08T02:42:58.791+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.358 seconds
[2024-12-08T02:43:29.802+0000] {processor.py:186} INFO - Started process (PID=722) to work on /opt/airflow/dags/weather.py
[2024-12-08T02:43:29.834+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T02:43:29.850+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:43:29.836+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T02:43:29.859+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:43:29.858+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 2, in <module>
    from airflow.providers.standard.operators.python import (
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2024-12-08T02:43:29.871+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-08T02:43:29.958+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.231 seconds
[2024-12-08T02:43:30.939+0000] {processor.py:186} INFO - Started process (PID=723) to work on /opt/airflow/dags/weather.py
[2024-12-08T02:43:30.940+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T02:43:30.943+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:43:30.942+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T02:43:30.949+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:43:30.948+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 2, in <module>
    from airflow.providers.operators.python import (
ModuleNotFoundError: No module named 'airflow.providers.operators'
[2024-12-08T02:43:30.950+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-08T02:43:31.018+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.111 seconds
[2024-12-08T02:44:01.305+0000] {processor.py:186} INFO - Started process (PID=730) to work on /opt/airflow/dags/weather.py
[2024-12-08T02:44:01.313+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T02:44:01.324+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:44:01.323+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T02:44:01.346+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:44:01.344+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 2, in <module>
    from airflow.providers.operators.python import (
ModuleNotFoundError: No module named 'airflow.providers.operators'
[2024-12-08T02:44:01.346+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-08T02:44:01.503+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.258 seconds
[2024-12-08T02:44:15.772+0000] {processor.py:186} INFO - Started process (PID=731) to work on /opt/airflow/dags/weather.py
[2024-12-08T02:44:15.779+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T02:44:15.789+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:44:15.782+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T02:44:15.802+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:44:15.801+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 2, in <module>
    from airflow.providers.standard.operators.python import (
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2024-12-08T02:44:15.803+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-08T02:44:15.881+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.152 seconds
[2024-12-08T02:44:22.073+0000] {processor.py:186} INFO - Started process (PID=738) to work on /opt/airflow/dags/weather.py
[2024-12-08T02:44:22.117+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T02:44:22.148+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:44:22.133+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T02:44:22.203+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:44:22.190+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 2, in <module>
    from airflow.providers.standard.operators.python import (
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2024-12-08T02:44:22.204+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-08T02:44:22.477+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.457 seconds
[2024-12-08T02:44:53.154+0000] {processor.py:186} INFO - Started process (PID=745) to work on /opt/airflow/dags/weather.py
[2024-12-08T02:44:53.167+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T02:44:53.183+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:44:53.170+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T02:44:53.230+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:44:53.221+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 2, in <module>
    from airflow.providers.standard.operators.python import (
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2024-12-08T02:44:53.240+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-08T02:44:53.323+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.212 seconds
[2024-12-08T02:45:23.900+0000] {processor.py:186} INFO - Started process (PID=752) to work on /opt/airflow/dags/weather.py
[2024-12-08T02:45:23.905+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T02:45:23.910+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:45:23.909+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T02:45:23.932+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:45:23.923+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 2, in <module>
    from airflow.providers.standard.operators.python import (
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2024-12-08T02:45:23.935+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-08T02:45:24.131+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.252 seconds
[2024-12-08T02:45:55.250+0000] {processor.py:186} INFO - Started process (PID=759) to work on /opt/airflow/dags/weather.py
[2024-12-08T02:45:55.259+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T02:45:55.271+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:45:55.262+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T02:45:55.288+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:45:55.281+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 2, in <module>
    from airflow.providers.standard.operators.python import (
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2024-12-08T02:45:55.289+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-08T02:45:55.426+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.254 seconds
[2024-12-08T02:46:26.046+0000] {processor.py:186} INFO - Started process (PID=767) to work on /opt/airflow/dags/weather.py
[2024-12-08T02:46:26.075+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T02:46:26.088+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:46:26.087+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T02:46:26.106+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:46:26.100+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 2, in <module>
    from airflow.providers.standard.operators.python import (
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2024-12-08T02:46:26.108+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-08T02:46:26.376+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.472 seconds
[2024-12-08T02:46:57.082+0000] {processor.py:186} INFO - Started process (PID=774) to work on /opt/airflow/dags/weather.py
[2024-12-08T02:46:57.097+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T02:46:57.112+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:46:57.112+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T02:46:57.162+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:46:57.134+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 2, in <module>
    from airflow.providers.standard.operators.python import (
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2024-12-08T02:46:57.163+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-08T02:46:57.259+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.209 seconds
[2024-12-08T02:47:27.980+0000] {processor.py:186} INFO - Started process (PID=780) to work on /opt/airflow/dags/weather.py
[2024-12-08T02:47:27.981+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T02:47:27.984+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:47:27.984+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T02:47:27.990+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:47:27.989+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 2, in <module>
    from airflow.providers.standard.operators.python import (
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2024-12-08T02:47:27.991+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-08T02:47:28.210+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.241 seconds
[2024-12-08T02:47:59.021+0000] {processor.py:186} INFO - Started process (PID=787) to work on /opt/airflow/dags/weather.py
[2024-12-08T02:47:59.042+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T02:47:59.055+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:47:59.053+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T02:47:59.069+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:47:59.068+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 2, in <module>
    from airflow.providers.standard.operators.python import (
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2024-12-08T02:47:59.074+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-08T02:47:59.171+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 0.165 seconds
[2024-12-08T02:48:02.497+0000] {processor.py:186} INFO - Started process (PID=788) to work on /opt/airflow/dags/weather.py
[2024-12-08T02:48:02.503+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T02:48:02.524+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:48:02.506+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T02:48:20.125+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:48:20.118+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 64, in <module>
    'owner': 'data_engineer',
NameError: name 'datetime' is not defined
[2024-12-08T02:48:20.125+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-08T02:48:20.253+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 17.887 seconds
[2024-12-08T02:48:34.964+0000] {processor.py:186} INFO - Started process (PID=796) to work on /opt/airflow/dags/weather.py
[2024-12-08T02:48:34.965+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T02:48:34.992+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:48:34.981+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T02:48:39.661+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:48:39.660+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 68, in <module>
    'on_failure_callback': error_handler.task_error,
NameError: name 'error_handler' is not defined
[2024-12-08T02:48:39.662+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-08T02:48:39.732+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 4.889 seconds
[2024-12-08T02:48:48.766+0000] {processor.py:186} INFO - Started process (PID=798) to work on /opt/airflow/dags/weather.py
[2024-12-08T02:48:48.770+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T02:48:48.778+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:48:48.777+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T02:48:51.601+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:48:51.599+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 68, in <module>
    'on_failure_callback': error_handler.task_error,
NameError: name 'error_handler' is not defined
[2024-12-08T02:48:51.601+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-08T02:48:51.669+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 2.924 seconds
[2024-12-08T02:49:17.356+0000] {processor.py:186} INFO - Started process (PID=806) to work on /opt/airflow/dags/weather.py
[2024-12-08T02:49:17.369+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T02:49:17.388+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:49:17.387+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T02:49:23.655+0000] {processor.py:925} INFO - DAG(s) 'weather' retrieved from /opt/airflow/dags/weather.py
[2024-12-08T02:49:25.591+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:49:25.590+0000] {override.py:1911} INFO - Created Permission View: can edit on DAG:weather
[2024-12-08T02:49:25.702+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:49:25.701+0000] {override.py:1911} INFO - Created Permission View: can delete on DAG:weather
[2024-12-08T02:49:25.764+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:49:25.762+0000] {override.py:1911} INFO - Created Permission View: can read on DAG:weather
[2024-12-08T02:49:25.893+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:49:25.892+0000] {override.py:1911} INFO - Created Permission View: menu access on DAG Run:weather
[2024-12-08T02:49:25.967+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:49:25.967+0000] {override.py:1911} INFO - Created Permission View: can create on DAG Run:weather
[2024-12-08T02:49:26.046+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:49:26.045+0000] {override.py:1911} INFO - Created Permission View: can delete on DAG Run:weather
[2024-12-08T02:49:26.208+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:49:26.208+0000] {override.py:1911} INFO - Created Permission View: can read on DAG Run:weather
[2024-12-08T02:49:26.209+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:49:26.209+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-08T02:49:26.350+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:49:26.349+0000] {dag.py:3262} INFO - Creating ORM DAG for weather
[2024-12-08T02:49:26.457+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:49:26.456+0000] {dag.py:4180} INFO - Setting next_dagrun for weather to 2024-12-07 00:00:00+00:00, run_after=2024-12-08 00:00:00+00:00
[2024-12-08T02:49:26.635+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 9.351 seconds
[2024-12-08T02:49:57.639+0000] {processor.py:186} INFO - Started process (PID=820) to work on /opt/airflow/dags/weather.py
[2024-12-08T02:49:57.646+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T02:49:57.663+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:49:57.662+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T02:50:03.055+0000] {processor.py:925} INFO - DAG(s) 'weather' retrieved from /opt/airflow/dags/weather.py
[2024-12-08T02:50:03.891+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:50:03.886+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-08T02:50:04.091+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:50:04.090+0000] {dag.py:4180} INFO - Setting next_dagrun for weather to 2024-12-07 00:00:00+00:00, run_after=2024-12-08 00:00:00+00:00
[2024-12-08T02:50:04.249+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 6.667 seconds
[2024-12-08T02:50:35.094+0000] {processor.py:186} INFO - Started process (PID=828) to work on /opt/airflow/dags/weather.py
[2024-12-08T02:50:35.108+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T02:50:35.125+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:50:35.125+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T02:50:42.185+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:50:42.158+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 62, in <module>
    with DAG(
TypeError: __init__() got an unexpected keyword argument 'scheduler'
[2024-12-08T02:50:42.200+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-08T02:50:42.324+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 7.283 seconds
[2024-12-08T02:51:12.769+0000] {processor.py:186} INFO - Started process (PID=836) to work on /opt/airflow/dags/weather.py
[2024-12-08T02:51:12.784+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T02:51:12.819+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:51:12.818+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T02:51:17.110+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:51:17.108+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 62, in <module>
    with DAG(
TypeError: __init__() got an unexpected keyword argument 'scheduler'
[2024-12-08T02:51:17.111+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-08T02:51:17.232+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 4.539 seconds
[2024-12-08T02:51:48.190+0000] {processor.py:186} INFO - Started process (PID=844) to work on /opt/airflow/dags/weather.py
[2024-12-08T02:51:48.194+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T02:51:48.197+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:51:48.197+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T02:51:54.715+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:51:54.704+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/weather.py", line 62, in <module>
    with DAG(
TypeError: __init__() got an unexpected keyword argument 'scheduler'
[2024-12-08T02:51:54.716+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/weather.py
[2024-12-08T02:51:54.820+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 6.656 seconds
[2024-12-08T02:52:16.350+0000] {processor.py:186} INFO - Started process (PID=852) to work on /opt/airflow/dags/weather.py
[2024-12-08T02:52:16.363+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T02:52:16.365+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:52:16.365+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T02:52:20.804+0000] {processor.py:925} INFO - DAG(s) 'weather' retrieved from /opt/airflow/dags/weather.py
[2024-12-08T02:52:21.013+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:52:21.012+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-08T02:52:21.055+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:52:21.054+0000] {dag.py:4180} INFO - Setting next_dagrun for weather to 2024-12-08 00:00:00+00:00, run_after=2024-12-09 00:00:00+00:00
[2024-12-08T02:52:21.183+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 4.885 seconds
[2024-12-08T02:52:51.633+0000] {processor.py:186} INFO - Started process (PID=860) to work on /opt/airflow/dags/weather.py
[2024-12-08T02:52:51.643+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T02:52:51.645+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:52:51.644+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T02:52:58.873+0000] {processor.py:925} INFO - DAG(s) 'weather' retrieved from /opt/airflow/dags/weather.py
[2024-12-08T02:52:59.019+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:52:59.019+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-08T02:52:59.079+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:52:59.078+0000] {dag.py:4180} INFO - Setting next_dagrun for weather to 2024-12-08 00:00:00+00:00, run_after=2024-12-09 00:00:00+00:00
[2024-12-08T02:52:59.178+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 7.633 seconds
[2024-12-08T02:53:29.769+0000] {processor.py:186} INFO - Started process (PID=874) to work on /opt/airflow/dags/weather.py
[2024-12-08T02:53:29.776+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T02:53:29.810+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:53:29.790+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T02:53:34.305+0000] {processor.py:925} INFO - DAG(s) 'weather' retrieved from /opt/airflow/dags/weather.py
[2024-12-08T02:53:34.398+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:53:34.397+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-08T02:53:34.528+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:53:34.527+0000] {dag.py:4180} INFO - Setting next_dagrun for weather to 2024-12-08 00:00:00+00:00, run_after=2024-12-09 00:00:00+00:00
[2024-12-08T02:53:34.653+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 4.904 seconds
[2024-12-08T02:54:05.749+0000] {processor.py:186} INFO - Started process (PID=882) to work on /opt/airflow/dags/weather.py
[2024-12-08T02:54:05.755+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T02:54:05.774+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:54:05.773+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T02:54:10.159+0000] {processor.py:925} INFO - DAG(s) 'weather' retrieved from /opt/airflow/dags/weather.py
[2024-12-08T02:54:10.410+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:54:10.397+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-08T02:54:10.613+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:54:10.613+0000] {dag.py:4180} INFO - Setting next_dagrun for weather to 2024-12-08 00:00:00+00:00, run_after=2024-12-09 00:00:00+00:00
[2024-12-08T02:54:10.803+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 5.129 seconds
[2024-12-08T02:54:41.119+0000] {processor.py:186} INFO - Started process (PID=890) to work on /opt/airflow/dags/weather.py
[2024-12-08T02:54:41.141+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T02:54:41.168+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:54:41.143+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T02:54:47.954+0000] {processor.py:925} INFO - DAG(s) 'weather' retrieved from /opt/airflow/dags/weather.py
[2024-12-08T02:54:48.165+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:54:48.165+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-08T02:54:48.379+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:54:48.378+0000] {dag.py:4180} INFO - Setting next_dagrun for weather to 2024-12-08 00:00:00+00:00, run_after=2024-12-09 00:00:00+00:00
[2024-12-08T02:54:48.696+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 7.630 seconds
[2024-12-08T02:55:19.148+0000] {processor.py:186} INFO - Started process (PID=897) to work on /opt/airflow/dags/weather.py
[2024-12-08T02:55:19.175+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T02:55:19.192+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:55:19.189+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T02:55:27.398+0000] {processor.py:925} INFO - DAG(s) 'weather' retrieved from /opt/airflow/dags/weather.py
[2024-12-08T02:55:27.719+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:55:27.700+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-08T02:55:28.140+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:55:28.140+0000] {dag.py:4180} INFO - Setting next_dagrun for weather to 2024-12-08 00:00:00+00:00, run_after=2024-12-09 00:00:00+00:00
[2024-12-08T02:55:28.485+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 9.459 seconds
[2024-12-08T02:55:59.072+0000] {processor.py:186} INFO - Started process (PID=905) to work on /opt/airflow/dags/weather.py
[2024-12-08T02:55:59.087+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T02:55:59.089+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:55:59.089+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T02:56:04.549+0000] {processor.py:925} INFO - DAG(s) 'weather' retrieved from /opt/airflow/dags/weather.py
[2024-12-08T02:56:04.715+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:56:04.714+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-08T02:56:04.899+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:56:04.899+0000] {dag.py:4180} INFO - Setting next_dagrun for weather to 2024-12-08 00:00:00+00:00, run_after=2024-12-09 00:00:00+00:00
[2024-12-08T02:56:04.975+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 5.993 seconds
[2024-12-08T02:56:36.143+0000] {processor.py:186} INFO - Started process (PID=919) to work on /opt/airflow/dags/weather.py
[2024-12-08T02:56:36.149+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T02:56:36.157+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:56:36.156+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T02:56:39.591+0000] {processor.py:925} INFO - DAG(s) 'weather' retrieved from /opt/airflow/dags/weather.py
[2024-12-08T02:56:39.951+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:56:39.950+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-08T02:56:40.203+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:56:40.202+0000] {dag.py:4180} INFO - Setting next_dagrun for weather to 2024-12-08 00:00:00+00:00, run_after=2024-12-09 00:00:00+00:00
[2024-12-08T02:56:40.366+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 4.279 seconds
[2024-12-08T02:57:11.391+0000] {processor.py:186} INFO - Started process (PID=926) to work on /opt/airflow/dags/weather.py
[2024-12-08T02:57:11.399+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T02:57:11.401+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:57:11.400+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T02:57:12.611+0000] {processor.py:925} INFO - DAG(s) 'weather' retrieved from /opt/airflow/dags/weather.py
[2024-12-08T02:57:12.907+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:57:12.906+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-08T02:57:13.179+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:57:13.178+0000] {dag.py:4180} INFO - Setting next_dagrun for weather to 2024-12-08 00:00:00+00:00, run_after=2024-12-09 00:00:00+00:00
[2024-12-08T02:57:13.467+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 2.228 seconds
[2024-12-08T02:57:44.272+0000] {processor.py:186} INFO - Started process (PID=933) to work on /opt/airflow/dags/weather.py
[2024-12-08T02:57:44.283+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T02:57:44.296+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:57:44.285+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T02:57:52.287+0000] {processor.py:925} INFO - DAG(s) 'weather' retrieved from /opt/airflow/dags/weather.py
[2024-12-08T02:57:52.431+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:57:52.431+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-08T02:57:52.731+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:57:52.730+0000] {dag.py:4180} INFO - Setting next_dagrun for weather to 2024-12-08 00:00:00+00:00, run_after=2024-12-09 00:00:00+00:00
[2024-12-08T02:57:52.980+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 8.747 seconds
[2024-12-08T02:58:23.586+0000] {processor.py:186} INFO - Started process (PID=941) to work on /opt/airflow/dags/weather.py
[2024-12-08T02:58:23.596+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T02:58:23.607+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:58:23.603+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T02:58:31.543+0000] {processor.py:925} INFO - DAG(s) 'weather' retrieved from /opt/airflow/dags/weather.py
[2024-12-08T02:58:31.729+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:58:31.728+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-08T02:58:32.314+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:58:32.313+0000] {dag.py:4180} INFO - Setting next_dagrun for weather to 2024-12-08 00:00:00+00:00, run_after=2024-12-09 00:00:00+00:00
[2024-12-08T02:58:32.589+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 9.027 seconds
[2024-12-08T02:59:03.639+0000] {processor.py:186} INFO - Started process (PID=949) to work on /opt/airflow/dags/weather.py
[2024-12-08T02:59:03.656+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T02:59:03.669+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:59:03.668+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T02:59:13.942+0000] {processor.py:925} INFO - DAG(s) 'weather' retrieved from /opt/airflow/dags/weather.py
[2024-12-08T02:59:14.181+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:59:14.178+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-08T02:59:14.482+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:59:14.469+0000] {dag.py:4180} INFO - Setting next_dagrun for weather to 2024-12-08 00:00:00+00:00, run_after=2024-12-09 00:00:00+00:00
[2024-12-08T02:59:14.805+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 11.254 seconds
[2024-12-08T02:59:45.365+0000] {processor.py:186} INFO - Started process (PID=964) to work on /opt/airflow/dags/weather.py
[2024-12-08T02:59:45.371+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T02:59:45.378+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:59:45.373+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T02:59:47.806+0000] {processor.py:925} INFO - DAG(s) 'weather' retrieved from /opt/airflow/dags/weather.py
[2024-12-08T02:59:48.110+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:59:48.102+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-08T02:59:48.225+0000] {logging_mixin.py:190} INFO - [2024-12-08T02:59:48.224+0000] {dag.py:4180} INFO - Setting next_dagrun for weather to 2024-12-08 00:00:00+00:00, run_after=2024-12-09 00:00:00+00:00
[2024-12-08T02:59:48.348+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 2.998 seconds
[2024-12-08T03:00:18.661+0000] {processor.py:186} INFO - Started process (PID=972) to work on /opt/airflow/dags/weather.py
[2024-12-08T03:00:18.665+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T03:00:18.670+0000] {logging_mixin.py:190} INFO - [2024-12-08T03:00:18.669+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T03:00:25.082+0000] {processor.py:925} INFO - DAG(s) 'weather' retrieved from /opt/airflow/dags/weather.py
[2024-12-08T03:00:25.482+0000] {logging_mixin.py:190} INFO - [2024-12-08T03:00:25.481+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-08T03:00:25.885+0000] {logging_mixin.py:190} INFO - [2024-12-08T03:00:25.885+0000] {dag.py:4180} INFO - Setting next_dagrun for weather to 2024-12-08 00:00:00+00:00, run_after=2024-12-09 00:00:00+00:00
[2024-12-08T03:00:26.156+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 7.521 seconds
[2024-12-08T03:00:57.112+0000] {processor.py:186} INFO - Started process (PID=980) to work on /opt/airflow/dags/weather.py
[2024-12-08T03:00:57.118+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T03:00:57.120+0000] {logging_mixin.py:190} INFO - [2024-12-08T03:00:57.120+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T03:01:02.002+0000] {processor.py:925} INFO - DAG(s) 'weather' retrieved from /opt/airflow/dags/weather.py
[2024-12-08T03:01:02.106+0000] {logging_mixin.py:190} INFO - [2024-12-08T03:01:02.103+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-08T03:01:02.242+0000] {logging_mixin.py:190} INFO - [2024-12-08T03:01:02.241+0000] {dag.py:4180} INFO - Setting next_dagrun for weather to 2024-12-08 00:00:00+00:00, run_after=2024-12-09 00:00:00+00:00
[2024-12-08T03:01:02.349+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 5.297 seconds
[2024-12-08T03:01:33.449+0000] {processor.py:186} INFO - Started process (PID=988) to work on /opt/airflow/dags/weather.py
[2024-12-08T03:01:33.453+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T03:01:33.455+0000] {logging_mixin.py:190} INFO - [2024-12-08T03:01:33.454+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T03:01:39.253+0000] {processor.py:925} INFO - DAG(s) 'weather' retrieved from /opt/airflow/dags/weather.py
[2024-12-08T03:01:39.384+0000] {logging_mixin.py:190} INFO - [2024-12-08T03:01:39.382+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-08T03:01:39.528+0000] {logging_mixin.py:190} INFO - [2024-12-08T03:01:39.527+0000] {dag.py:4180} INFO - Setting next_dagrun for weather to 2024-12-08 00:00:00+00:00, run_after=2024-12-09 00:00:00+00:00
[2024-12-08T03:01:39.642+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 6.245 seconds
[2024-12-08T03:02:10.827+0000] {processor.py:186} INFO - Started process (PID=1004) to work on /opt/airflow/dags/weather.py
[2024-12-08T03:02:10.841+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T03:02:10.843+0000] {logging_mixin.py:190} INFO - [2024-12-08T03:02:10.843+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T03:02:13.107+0000] {processor.py:925} INFO - DAG(s) 'weather' retrieved from /opt/airflow/dags/weather.py
[2024-12-08T03:02:13.275+0000] {logging_mixin.py:190} INFO - [2024-12-08T03:02:13.268+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-08T03:02:13.537+0000] {logging_mixin.py:190} INFO - [2024-12-08T03:02:13.535+0000] {dag.py:4180} INFO - Setting next_dagrun for weather to 2024-12-08 00:00:00+00:00, run_after=2024-12-09 00:00:00+00:00
[2024-12-08T03:02:13.702+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 2.988 seconds
[2024-12-08T03:02:44.726+0000] {processor.py:186} INFO - Started process (PID=1011) to work on /opt/airflow/dags/weather.py
[2024-12-08T03:02:44.729+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T03:02:44.737+0000] {logging_mixin.py:190} INFO - [2024-12-08T03:02:44.736+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T03:02:49.806+0000] {processor.py:925} INFO - DAG(s) 'weather' retrieved from /opt/airflow/dags/weather.py
[2024-12-08T03:02:49.951+0000] {logging_mixin.py:190} INFO - [2024-12-08T03:02:49.949+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-08T03:02:50.060+0000] {logging_mixin.py:190} INFO - [2024-12-08T03:02:50.060+0000] {dag.py:4180} INFO - Setting next_dagrun for weather to 2024-12-08 00:00:00+00:00, run_after=2024-12-09 00:00:00+00:00
[2024-12-08T03:02:50.155+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 5.455 seconds
[2024-12-08T03:03:20.934+0000] {processor.py:186} INFO - Started process (PID=1019) to work on /opt/airflow/dags/weather.py
[2024-12-08T03:03:20.948+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T03:03:21.005+0000] {logging_mixin.py:190} INFO - [2024-12-08T03:03:20.957+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T03:03:25.403+0000] {processor.py:925} INFO - DAG(s) 'weather' retrieved from /opt/airflow/dags/weather.py
[2024-12-08T03:03:25.653+0000] {logging_mixin.py:190} INFO - [2024-12-08T03:03:25.649+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-08T03:03:25.906+0000] {logging_mixin.py:190} INFO - [2024-12-08T03:03:25.905+0000] {dag.py:4180} INFO - Setting next_dagrun for weather to 2024-12-08 00:00:00+00:00, run_after=2024-12-09 00:00:00+00:00
[2024-12-08T03:03:26.145+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 5.309 seconds
[2024-12-08T03:03:57.189+0000] {processor.py:186} INFO - Started process (PID=1026) to work on /opt/airflow/dags/weather.py
[2024-12-08T03:03:57.190+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T03:03:57.194+0000] {logging_mixin.py:190} INFO - [2024-12-08T03:03:57.192+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T03:04:03.031+0000] {processor.py:925} INFO - DAG(s) 'weather' retrieved from /opt/airflow/dags/weather.py
[2024-12-08T03:04:03.243+0000] {logging_mixin.py:190} INFO - [2024-12-08T03:04:03.235+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-08T03:04:03.563+0000] {logging_mixin.py:190} INFO - [2024-12-08T03:04:03.563+0000] {dag.py:4180} INFO - Setting next_dagrun for weather to 2024-12-08 00:00:00+00:00, run_after=2024-12-09 00:00:00+00:00
[2024-12-08T03:04:03.779+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 6.606 seconds
[2024-12-08T03:04:35.036+0000] {processor.py:186} INFO - Started process (PID=1034) to work on /opt/airflow/dags/weather.py
[2024-12-08T03:04:35.065+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T03:04:35.075+0000] {logging_mixin.py:190} INFO - [2024-12-08T03:04:35.072+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T03:04:40.850+0000] {processor.py:925} INFO - DAG(s) 'weather' retrieved from /opt/airflow/dags/weather.py
[2024-12-08T03:04:40.957+0000] {logging_mixin.py:190} INFO - [2024-12-08T03:04:40.957+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-08T03:04:41.033+0000] {logging_mixin.py:190} INFO - [2024-12-08T03:04:41.028+0000] {dag.py:4180} INFO - Setting next_dagrun for weather to 2024-12-08 00:00:00+00:00, run_after=2024-12-09 00:00:00+00:00
[2024-12-08T03:04:41.110+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 6.144 seconds
[2024-12-08T03:05:11.348+0000] {processor.py:186} INFO - Started process (PID=1041) to work on /opt/airflow/dags/weather.py
[2024-12-08T03:05:11.354+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T03:05:11.362+0000] {logging_mixin.py:190} INFO - [2024-12-08T03:05:11.358+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T03:05:14.498+0000] {processor.py:925} INFO - DAG(s) 'weather' retrieved from /opt/airflow/dags/weather.py
[2024-12-08T03:05:14.692+0000] {logging_mixin.py:190} INFO - [2024-12-08T03:05:14.691+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-08T03:05:14.934+0000] {logging_mixin.py:190} INFO - [2024-12-08T03:05:14.934+0000] {dag.py:4180} INFO - Setting next_dagrun for weather to 2024-12-08 00:00:00+00:00, run_after=2024-12-09 00:00:00+00:00
[2024-12-08T03:05:15.129+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 3.790 seconds
[2024-12-08T03:05:45.579+0000] {processor.py:186} INFO - Started process (PID=1054) to work on /opt/airflow/dags/weather.py
[2024-12-08T03:05:45.587+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T03:05:45.594+0000] {logging_mixin.py:190} INFO - [2024-12-08T03:05:45.588+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T03:05:50.576+0000] {processor.py:925} INFO - DAG(s) 'weather' retrieved from /opt/airflow/dags/weather.py
[2024-12-08T03:05:50.714+0000] {logging_mixin.py:190} INFO - [2024-12-08T03:05:50.714+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-08T03:05:50.915+0000] {logging_mixin.py:190} INFO - [2024-12-08T03:05:50.914+0000] {dag.py:4180} INFO - Setting next_dagrun for weather to 2024-12-08 00:00:00+00:00, run_after=2024-12-09 00:00:00+00:00
[2024-12-08T03:05:51.104+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 5.569 seconds
[2024-12-08T03:06:21.442+0000] {processor.py:186} INFO - Started process (PID=1062) to work on /opt/airflow/dags/weather.py
[2024-12-08T03:06:21.463+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T03:06:21.481+0000] {logging_mixin.py:190} INFO - [2024-12-08T03:06:21.469+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T03:06:23.861+0000] {processor.py:925} INFO - DAG(s) 'weather' retrieved from /opt/airflow/dags/weather.py
[2024-12-08T03:06:23.904+0000] {logging_mixin.py:190} INFO - [2024-12-08T03:06:23.903+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-08T03:06:23.960+0000] {logging_mixin.py:190} INFO - [2024-12-08T03:06:23.959+0000] {dag.py:4180} INFO - Setting next_dagrun for weather to 2024-12-08 00:00:00+00:00, run_after=2024-12-09 00:00:00+00:00
[2024-12-08T03:06:24.034+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 2.664 seconds
[2024-12-08T03:06:55.165+0000] {processor.py:186} INFO - Started process (PID=1070) to work on /opt/airflow/dags/weather.py
[2024-12-08T03:06:55.212+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T03:06:55.234+0000] {logging_mixin.py:190} INFO - [2024-12-08T03:06:55.223+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T03:06:59.998+0000] {processor.py:925} INFO - DAG(s) 'weather' retrieved from /opt/airflow/dags/weather.py
[2024-12-08T03:07:00.103+0000] {logging_mixin.py:190} INFO - [2024-12-08T03:07:00.102+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-08T03:07:00.217+0000] {logging_mixin.py:190} INFO - [2024-12-08T03:07:00.216+0000] {dag.py:4180} INFO - Setting next_dagrun for weather to 2024-12-08 00:00:00+00:00, run_after=2024-12-09 00:00:00+00:00
[2024-12-08T03:07:00.291+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 5.282 seconds
[2024-12-08T03:07:31.342+0000] {processor.py:186} INFO - Started process (PID=1078) to work on /opt/airflow/dags/weather.py
[2024-12-08T03:07:31.357+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T03:07:31.363+0000] {logging_mixin.py:190} INFO - [2024-12-08T03:07:31.358+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T03:07:38.180+0000] {processor.py:925} INFO - DAG(s) 'weather' retrieved from /opt/airflow/dags/weather.py
[2024-12-08T03:07:38.300+0000] {logging_mixin.py:190} INFO - [2024-12-08T03:07:38.299+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-08T03:07:38.360+0000] {logging_mixin.py:190} INFO - [2024-12-08T03:07:38.360+0000] {dag.py:4180} INFO - Setting next_dagrun for weather to 2024-12-08 00:00:00+00:00, run_after=2024-12-09 00:00:00+00:00
[2024-12-08T03:07:38.591+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 7.330 seconds
[2024-12-08T03:08:09.232+0000] {processor.py:186} INFO - Started process (PID=1086) to work on /opt/airflow/dags/weather.py
[2024-12-08T03:08:09.254+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T03:08:09.306+0000] {logging_mixin.py:190} INFO - [2024-12-08T03:08:09.288+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T03:08:13.115+0000] {processor.py:925} INFO - DAG(s) 'weather' retrieved from /opt/airflow/dags/weather.py
[2024-12-08T03:08:13.428+0000] {logging_mixin.py:190} INFO - [2024-12-08T03:08:13.427+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-08T03:08:13.876+0000] {logging_mixin.py:190} INFO - [2024-12-08T03:08:13.867+0000] {dag.py:4180} INFO - Setting next_dagrun for weather to 2024-12-08 00:00:00+00:00, run_after=2024-12-09 00:00:00+00:00
[2024-12-08T03:08:14.085+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 4.964 seconds
[2024-12-08T03:08:45.400+0000] {processor.py:186} INFO - Started process (PID=1094) to work on /opt/airflow/dags/weather.py
[2024-12-08T03:08:45.421+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T03:08:45.438+0000] {logging_mixin.py:190} INFO - [2024-12-08T03:08:45.437+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T03:08:53.914+0000] {processor.py:925} INFO - DAG(s) 'weather' retrieved from /opt/airflow/dags/weather.py
[2024-12-08T03:08:54.265+0000] {logging_mixin.py:190} INFO - [2024-12-08T03:08:54.264+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-08T03:08:54.459+0000] {logging_mixin.py:190} INFO - [2024-12-08T03:08:54.459+0000] {dag.py:4180} INFO - Setting next_dagrun for weather to 2024-12-08 00:00:00+00:00, run_after=2024-12-09 00:00:00+00:00
[2024-12-08T03:08:54.609+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 9.317 seconds
[2024-12-08T03:09:25.388+0000] {processor.py:186} INFO - Started process (PID=1108) to work on /opt/airflow/dags/weather.py
[2024-12-08T03:09:25.397+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/weather.py for tasks to queue
[2024-12-08T03:09:25.407+0000] {logging_mixin.py:190} INFO - [2024-12-08T03:09:25.401+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/weather.py
[2024-12-08T03:09:31.377+0000] {processor.py:925} INFO - DAG(s) 'weather' retrieved from /opt/airflow/dags/weather.py
[2024-12-08T03:09:31.575+0000] {logging_mixin.py:190} INFO - [2024-12-08T03:09:31.575+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-12-08T03:09:31.784+0000] {logging_mixin.py:190} INFO - [2024-12-08T03:09:31.784+0000] {dag.py:4180} INFO - Setting next_dagrun for weather to 2024-12-08 00:00:00+00:00, run_after=2024-12-09 00:00:00+00:00
[2024-12-08T03:09:32.016+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/weather.py took 6.669 seconds
